spring:
  application:
    name: FIRST-SERVICE-PROVIDER
server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    # 声明是否将自己的注册信息注册到Eureka服务器上,默认值为true
    register-with-eureka: true
    # 是否到Eureka服务器中抓取注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/