server:
  port: 8761
spring:
  application:
    name: eureka-server
  config:
    activate:
      on-profile: slave1
eureka:
  instance:
    hostname: slave1
  client:
    # 声明是否将自己的注册信息注册到Eureka服务器上,默认值为true
    register-with-eureka: false
    # 是否到Eureka服务器中抓取注册信息，默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/

---
server:
  port: 8762
spring:
  application:
    name: eureka-server
  config:
    activate:
      on-profile: slave2
eureka:
  instance:
    hostname: slave2
  client:
    # 声明是否将自己的注册信息注册到Eureka服务器上,默认值为true
    register-with-eureka: false
    # 是否到Eureka服务器中抓取注册信息，默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/